export enum BulkOp {
    CreateAll = 'create-all',
    CreateOne = 'create-one',
    Delete404 = 'delete-404',
    DeleteAll = 'delete-all',
    DeleteAny = 'delete-any',
    DeleteOne = 'delete-one',
    Select404 = 'select-404',
    SelectAll = 'select-all',
    SelectOne = 'select-one',
    Update404 = 'update-404',
    UpdateAll = 'update-all',
    UpdateAny = 'update-any',
    UpdateOne = 'update-one',
    UpsertAll = 'upsert-all',
    UpsertOne = 'upsert-one',
};
